# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_58",
    srcs = [
        "hardware-info.c",
        "ovmf-log.c",
        "var-service-auth.c",
        "var-service-core.c",
        "var-service-guid.c",
        "var-service-json.c",
        "var-service-pcap.c",
        "var-service-pkcs7-stub.c",
        "var-service-policy.c",
        "var-service-siglist.c",
        "var-service-sysbus.c",
        "var-service-utils.c",
        "var-service-vars.c",
    ],
)

filegroup(
    name = "trace-events__68",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_uefi",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
