# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "qemuutil_fg_18",
    srcs = [
        "mos6522-stub.c",
    ],
)

filegroup(
    name = "system_fg_37",
    srcs = [
        "a9scu.c",
        "allwinner-a10-ccm.c",
        "allwinner-a10-dramc.c",
        "allwinner-cpucfg.c",
        "allwinner-h3-ccu.c",
        "allwinner-h3-dramc.c",
        "allwinner-h3-sysctrl.c",
        "allwinner-r40-ccu.c",
        "allwinner-r40-dramc.c",
        "allwinner-sid.c",
        "allwinner-sramc.c",
        "applesmc.c",
        "arm11scu.c",
        "arm_integrator_debug.c",
        "arm_l2x0.c",
        "arm_sysctl.c",
        "armsse-cpu-pwrctrl.c",
        "armsse-cpuid.c",
        "armsse-mhu.c",
        "armv7m_ras.c",
        "aspeed_hace.c",
        "aspeed_lpc.c",
        "aspeed_ltpi.c",
        "aspeed_peci.c",
        "aspeed_pwm.c",
        "aspeed_sbc.c",
        "aspeed_scu.c",
        "aspeed_sdmc.c",
        "aspeed_sli.c",
        "aspeed_xdma.c",
        "auxbus.c",
        "avr_power.c",
        "axp2xx.c",
        "bcm2835_cprman.c",
        "bcm2835_mbox.c",
        "bcm2835_mphi.c",
        "bcm2835_powermgt.c",
        "bcm2835_property.c",
        "bcm2835_rng.c",
        "bcm2835_thermal.c",
        "debugexit.c",
        "djmemc.c",
        "eccmemctl.c",
        "edu.c",
        "empty_slot.c",
        "exynos4210_clk.c",
        "exynos4210_pmu.c",
        "exynos4210_rng.c",
        "grlib_ahb_apb_pnp.c",
        "i2c-echo.c",
        "imx25_ccm.c",
        "imx31_ccm.c",
        "imx6_ccm.c",
        "imx6_src.c",
        "imx6ul_ccm.c",
        "imx7_ccm.c",
        "imx7_gpr.c",
        "imx7_snvs.c",
        "imx7_src.c",
        "imx8mp_analog.c",
        "imx8mp_ccm.c",
        "imx_ccm.c",
        "imx_rngc.c",
        "iommu-testdev.c",
        "iosb.c",
        "iotkit-secctl.c",
        "iotkit-sysctl.c",
        "iotkit-sysinfo.c",
        "ivshmem-flat.c",
        "ivshmem-pci.c",
        "lasi.c",
        "led.c",
        "mac_via.c",
        "max78000_aes.c",
        "max78000_gcr.c",
        "max78000_icc.c",
        "max78000_trng.c",
        "mchp_pfsoc_dmc.c",
        "mchp_pfsoc_ioscb.c",
        "mchp_pfsoc_sysreg.c",
        "mos6522.c",
        "mps2-fpgaio.c",
        "mps2-scc.c",
        "msf2-sysreg.c",
        "npcm7xx_mft.c",
        "npcm7xx_pwm.c",
        "npcm7xx_rng.c",
        "npcm_clk.c",
        "npcm_gcr.c",
        "nrf51_rng.c",
        "omap_clk.c",
        "pc-testdev.c",
        "pci-testdev.c",
        "pvpanic-isa.c",
        "pvpanic-mmio.c",
        "pvpanic-pci.c",
        "pvpanic.c",
        "sbsa_ec.c",
        "sifive_e_aon.c",
        "sifive_e_prci.c",
        "sifive_test.c",
        "sifive_u_otp.c",
        "sifive_u_prci.c",
        "slavio_misc.c",
        "stm32_rcc.c",
        "stm32f2xx_syscfg.c",
        "stm32f4xx_exti.c",
        "stm32f4xx_syscfg.c",
        "stm32l4x5_exti.c",
        "stm32l4x5_rcc.c",
        "stm32l4x5_syscfg.c",
        "tz-mpc.c",
        "tz-msc.c",
        "tz-ppc.c",
        "unimp.c",
        "virt_ctrl.c",
        "vmcoreinfo.c",
        "xlnx-cfi-if.c",
        "xlnx-versal-cframe-reg.c",
        "xlnx-versal-cfu.c",
        "xlnx-versal-crl.c",
        "xlnx-versal-pmc-iou-slcr.c",
        "xlnx-versal-trng.c",
        "xlnx-versal-xramc.c",
        "xlnx-zynqmp-apu-ctrl.c",
        "xlnx-zynqmp-crf.c",
        "zynq_slcr.c",
    ],
)

filegroup(
    name = "trace-events__45",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_misc",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
