# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_library", "meson_genrule")

meson_genrule(
    name = "Test QAPI files",
    outs = [
        "qapi-builtin-types.c",
        "qapi-builtin-types.h",
        "qapi-builtin-visit.c",
        "qapi-builtin-visit.h",
        "test-qapi-commands-sub-sub-module.c",
        "test-qapi-commands-sub-sub-module.h",
        "test-qapi-commands.c",
        "test-qapi-commands.h",
        "test-qapi-emit-events.c",
        "test-qapi-emit-events.h",
        "test-qapi-events-sub-sub-module.c",
        "test-qapi-events-sub-sub-module.h",
        "test-qapi-events.c",
        "test-qapi-events.h",
        "test-qapi-features.c",
        "test-qapi-features.h",
        "test-qapi-init-commands.c",
        "test-qapi-init-commands.h",
        "test-qapi-introspect.c",
        "test-qapi-introspect.h",
        "test-qapi-types-sub-sub-module.c",
        "test-qapi-types-sub-sub-module.h",
        "test-qapi-types.c",
        "test-qapi-types.h",
        "test-qapi-visit-sub-sub-module.c",
        "test-qapi-visit-sub-sub-module.h",
        "test-qapi-visit.c",
        "test-qapi-visit.h",
    ],
    srcs = [
        "//scripts/qapi:__init___py",
        "//scripts/qapi:backend_py",
        "//scripts/qapi:commands_py",
        "//scripts/qapi:common_py",
        "//scripts/qapi:error_py",
        "//scripts/qapi:events_py",
        "//scripts/qapi:expr_py",
        "//scripts/qapi:features_py",
        "//scripts/qapi:gen_py",
        "//scripts/qapi:introspect_py",
        "//scripts/qapi:main_py",
        "//scripts/qapi:parser_py",
        "//scripts/qapi:schema_py",
        "//scripts/qapi:source_py",
        "//scripts/qapi:types_py",
        "//scripts/qapi:visit_py",
        "//scripts:qapi-gen_py",
        "//tests/qapi-schema/include:sub-module_json",
        "//tests/qapi-schema:qapi-schema-test_json",
        "//tests/qapi-schema:sub-sub-module_json",
    ],
    tools = [
        "//scripts:qapi-py_binary",
    ],
    export_include_dirs = [
        "tests",
    ],
    cmd = "$(location //scripts:qapi-py_binary) -o $(GENDIR) -b -p test- $(location //tests/qapi-schema:qapi-schema-test_json) --suppress-tracing",
)

meson_cc_library(
    name = "testqapi",
    deps = [
        "///usr/local/google/home/pefoley/qemu:inc__usr_local_google_home_pefoley_qemu",
        "//:config-poison.h",
        "//:hmp-commands-info.h",
        "//:hmp-commands.h",
        "//:qemu-img-cmds.h",
        "//:qemu-version.h",
        "//:qemu_c_project_args",
        "//qapi:shared QAPI source files",
        "//tests/include:QAPI test (include)",
        "//tests:Test QAPI files",
        "//trace:trace-accel_hvf.h",
        "//trace:trace-accel_kvm.h",
        "//trace:trace-accel_mshv.h",
        "//trace:trace-accel_nitro.h",
        "//trace:trace-accel_tcg.h",
        "//trace:trace-audio.h",
        "//trace:trace-authz.h",
        "//trace:trace-backends.h",
        "//trace:trace-backends_tpm.h",
        "//trace:trace-block.h",
        "//trace:trace-chardev.h",
        "//trace:trace-crypto.h",
        "//trace:trace-ebpf.h",
        "//trace:trace-gdbstub.h",
        "//trace:trace-hw_9pfs.h",
        "//trace:trace-hw_acpi.h",
        "//trace:trace-hw_adc.h",
        "//trace:trace-hw_alpha.h",
        "//trace:trace-hw_arm.h",
        "//trace:trace-hw_audio.h",
        "//trace:trace-hw_block.h",
        "//trace:trace-hw_char.h",
        "//trace:trace-hw_core.h",
        "//trace:trace-hw_display.h",
        "//trace:trace-hw_dma.h",
        "//trace:trace-hw_fsi.h",
        "//trace:trace-hw_gpio.h",
        "//trace:trace-hw_hyperv.h",
        "//trace:trace-hw_i2c.h",
        "//trace:trace-hw_i386.h",
        "//trace:trace-hw_i386_kvm.h",
        "//trace:trace-hw_i386_xen.h",
        "//trace:trace-hw_i3c.h",
        "//trace:trace-hw_ide.h",
        "//trace:trace-hw_input.h",
        "//trace:trace-hw_intc.h",
        "//trace:trace-hw_isa.h",
        "//trace:trace-hw_mem.h",
        "//trace:trace-hw_mips.h",
        "//trace:trace-hw_misc.h",
        "//trace:trace-hw_misc_macio.h",
        "//trace:trace-hw_net.h",
        "//trace:trace-hw_net_can.h",
        "//trace:trace-hw_nitro.h",
        "//trace:trace-hw_nubus.h",
        "//trace:trace-hw_nvme.h",
        "//trace:trace-hw_nvram.h",
        "//trace:trace-hw_pci.h",
        "//trace:trace-hw_pci_host.h",
        "//trace:trace-hw_ppc.h",
        "//trace:trace-hw_remote.h",
        "//trace:trace-hw_riscv.h",
        "//trace:trace-hw_rtc.h",
        "//trace:trace-hw_s390x.h",
        "//trace:trace-hw_scsi.h",
        "//trace:trace-hw_sd.h",
        "//trace:trace-hw_sensor.h",
        "//trace:trace-hw_sh4.h",
        "//trace:trace-hw_sparc.h",
        "//trace:trace-hw_sparc64.h",
        "//trace:trace-hw_ssi.h",
        "//trace:trace-hw_timer.h",
        "//trace:trace-hw_tpm.h",
        "//trace:trace-hw_uefi.h",
        "//trace:trace-hw_ufs.h",
        "//trace:trace-hw_usb.h",
        "//trace:trace-hw_vfio.h",
        "//trace:trace-hw_vfio_user.h",
        "//trace:trace-hw_virtio.h",
        "//trace:trace-hw_vmapple.h",
        "//trace:trace-hw_watchdog.h",
        "//trace:trace-hw_xen.h",
        "//trace:trace-io.h",
        "//trace:trace-migration.h",
        "//trace:trace-monitor.h",
        "//trace:trace-nbd.h",
        "//trace:trace-net.h",
        "//trace:trace-qapi.h",
        "//trace:trace-qapi_commands_accelerator_trace_events.h",
        "//trace:trace-qapi_commands_acpi_hest_trace_events.h",
        "//trace:trace-qapi_commands_acpi_trace_events.h",
        "//trace:trace-qapi_commands_audio_trace_events.h",
        "//trace:trace-qapi_commands_authz_trace_events.h",
        "//trace:trace-qapi_commands_block_core_trace_events.h",
        "//trace:trace-qapi_commands_block_export_trace_events.h",
        "//trace:trace-qapi_commands_block_trace_events.h",
        "//trace:trace-qapi_commands_char_trace_events.h",
        "//trace:trace-qapi_commands_common_trace_events.h",
        "//trace:trace-qapi_commands_compat_trace_events.h",
        "//trace:trace-qapi_commands_control_trace_events.h",
        "//trace:trace-qapi_commands_crypto_trace_events.h",
        "//trace:trace-qapi_commands_cryptodev_trace_events.h",
        "//trace:trace-qapi_commands_cxl_trace_events.h",
        "//trace:trace-qapi_commands_dump_trace_events.h",
        "//trace:trace-qapi_commands_ebpf_trace_events.h",
        "//trace:trace-qapi_commands_error_trace_events.h",
        "//trace:trace-qapi_commands_introspect_trace_events.h",
        "//trace:trace-qapi_commands_job_trace_events.h",
        "//trace:trace-qapi_commands_machine_common_trace_events.h",
        "//trace:trace-qapi_commands_machine_s390x_trace_events.h",
        "//trace:trace-qapi_commands_machine_trace_events.h",
        "//trace:trace-qapi_commands_migration_trace_events.h",
        "//trace:trace-qapi_commands_misc_arm_trace_events.h",
        "//trace:trace-qapi_commands_misc_i386_trace_events.h",
        "//trace:trace-qapi_commands_misc_trace_events.h",
        "//trace:trace-qapi_commands_net_trace_events.h",
        "//trace:trace-qapi_commands_pci_trace_events.h",
        "//trace:trace-qapi_commands_pragma_trace_events.h",
        "//trace:trace-qapi_commands_qdev_trace_events.h",
        "//trace:trace-qapi_commands_qom_trace_events.h",
        "//trace:trace-qapi_commands_replay_trace_events.h",
        "//trace:trace-qapi_commands_rocker_trace_events.h",
        "//trace:trace-qapi_commands_run_state_trace_events.h",
        "//trace:trace-qapi_commands_sockets_trace_events.h",
        "//trace:trace-qapi_commands_stats_trace_events.h",
        "//trace:trace-qapi_commands_tpm_trace_events.h",
        "//trace:trace-qapi_commands_trace_trace_events.h",
        "//trace:trace-qapi_commands_transaction_trace_events.h",
        "//trace:trace-qapi_commands_uefi_trace_events.h",
        "//trace:trace-qapi_commands_ui_trace_events.h",
        "//trace:trace-qapi_commands_vfio_trace_events.h",
        "//trace:trace-qapi_commands_virtio_trace_events.h",
        "//trace:trace-qapi_commands_yank_trace_events.h",
        "//trace:trace-qom.h",
        "//trace:trace-replay.h",
        "//trace:trace-root.h",
        "//trace:trace-scsi.h",
        "//trace:trace-system.h",
        "//trace:trace-target_arm.h",
        "//trace:trace-target_arm_hvf.h",
        "//trace:trace-target_arm_tcg.h",
        "//trace:trace-target_hppa.h",
        "//trace:trace-target_i386.h",
        "//trace:trace-target_i386_kvm.h",
        "//trace:trace-target_i386_whpx.h",
        "//trace:trace-target_loongarch.h",
        "//trace:trace-target_mips_tcg.h",
        "//trace:trace-target_ppc.h",
        "//trace:trace-target_riscv.h",
        "//trace:trace-target_s390x.h",
        "//trace:trace-target_s390x_kvm.h",
        "//trace:trace-target_sparc.h",
        "//trace:trace-tools_qemu_vnc.h",
        "//trace:trace-ui.h",
        "//trace:trace-util.h",
        "//ui/shader:texture-blit-flip-vert.h",
        "//ui/shader:texture-blit-frag.h",
        "//ui/shader:texture-blit-vert.h",
    ],
)
