# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_51",
    srcs = [
        "emulation.c",
        "esp-pci.c",
        "esp.c",
        "lasi_ncr710.c",
        "lsi53c895a.c",
        "megasas.c",
        "mptconfig.c",
        "mptendian.c",
        "mptsas.c",
        "ncr53c710.c",
        "scsi-bus.c",
        "scsi-disk.c",
        "scsi-generic.c",
        "vhost-scsi-common.c",
        "vhost-scsi.c",
        "vhost-user-scsi.c",
        "virtio-scsi-dataplane.c",
        "virtio-scsi.c",
        "vmw_pvscsi.c",
    ],
)

filegroup(
    name = "trace-events__59",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_scsi",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
