# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_30",
    srcs = [
        "ahci-allwinner.c",
        "ahci-sysbus.c",
        "ahci.c",
        "atapi.c",
        "cf.c",
        "cmd646.c",
        "core.c",
        "ich.c",
        "ide-bus.c",
        "ide-dev.c",
        "ioport.c",
        "isa.c",
        "macio.c",
        "mmio.c",
        "pci.c",
        "piix.c",
        "sii3112.c",
        "via.c",
    ],
)

filegroup(
    name = "trace-events__39",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_ide",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
