# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_genrule")

meson_genrule(
    name = "QAPI files for qemu-storage-daemon",
    outs = [
        "qapi-commands.c",
        "qapi-commands.h",
        "qapi-emit-events.c",
        "qapi-emit-events.h",
        "qapi-events.c",
        "qapi-events.h",
        "qapi-init-commands.c",
        "qapi-init-commands.h",
        "qapi-introspect.c",
        "qapi-introspect.h",
        "qapi-types.c",
        "qapi-types.h",
        "qapi-visit.c",
        "qapi-visit.h",
    ],
    srcs = [
        "//qapi:accelerator_json",
        "//qapi:acpi-hest_json",
        "//qapi:acpi_json",
        "//qapi:audio_json",
        "//qapi:authz_json",
        "//qapi:block-core_json",
        "//qapi:block-export_json",
        "//qapi:block_json",
        "//qapi:char_json",
        "//qapi:common_json",
        "//qapi:compat_json",
        "//qapi:control_json",
        "//qapi:crypto_json",
        "//qapi:cryptodev_json",
        "//qapi:cxl_json",
        "//qapi:dump_json",
        "//qapi:ebpf_json",
        "//qapi:error_json",
        "//qapi:introspect_json",
        "//qapi:job_json",
        "//qapi:machine-common_json",
        "//qapi:machine-s390x_json",
        "//qapi:machine_json",
        "//qapi:migration_json",
        "//qapi:misc-arm_json",
        "//qapi:misc-i386_json",
        "//qapi:misc_json",
        "//qapi:net_json",
        "//qapi:pci_json",
        "//qapi:pragma_json",
        "//qapi:qdev_json",
        "//qapi:qom_json",
        "//qapi:replay_json",
        "//qapi:rocker_json",
        "//qapi:run-state_json",
        "//qapi:sockets_json",
        "//qapi:stats_json",
        "//qapi:tpm_json",
        "//qapi:trace_json",
        "//qapi:transaction_json",
        "//qapi:uefi_json",
        "//qapi:ui_json",
        "//qapi:vfio_json",
        "//qapi:virtio_json",
        "//qapi:yank_json",
        "//scripts/qapi:__init___py",
        "//scripts/qapi:backend_py",
        "//scripts/qapi:commands_py",
        "//scripts/qapi:common_py",
        "//scripts/qapi:error_py",
        "//scripts/qapi:events_py",
        "//scripts/qapi:expr_py",
        "//scripts/qapi:features_py",
        "//scripts/qapi:gen_py",
        "//scripts/qapi:introspect_py",
        "//scripts/qapi:main_py",
        "//scripts/qapi:parser_py",
        "//scripts/qapi:schema_py",
        "//scripts/qapi:source_py",
        "//scripts/qapi:types_py",
        "//scripts/qapi:visit_py",
        "//scripts:qapi-gen_py",
        "qapi-schema.json",
    ],
    tools = [
        "//scripts:qapi-py_binary",
    ],
    export_include_dirs = [
        "storage-daemon",
        "storage-daemon/qapi",
    ],
    cmd = "$(location //scripts:qapi-py_binary) -o storage-daemon/qapi $(location qapi-schema.json)",
)
