# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "blockdev_fg_1",
    srcs = [
        "export.c",
        "vduse-blk.c",
        "vhost-user-blk-server.c",
        "virtio-blk-handler.c",
    ],
)

meson_cc_headers(
    name = "inc_block_export",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
