# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_genrule")

meson_genrule(
    name = "texture-blit-flip-vert.h",
    outs = [
        "texture-blit-flip-vert.h",
    ],
    srcs = [
        "texture-blit-flip.vert",
    ],
    tools = [
        "//scripts:shaderinclude_py_binary",
    ],
    export_include_dirs = [
        "ui",
        "ui/shader",
    ],
    cmd = "$(location //scripts:shaderinclude_py_binary) $(location texture-blit-flip.vert) > $(location texture-blit-flip-vert.h)",
)

meson_genrule(
    name = "texture-blit-frag.h",
    outs = [
        "texture-blit-frag.h",
    ],
    srcs = [
        "texture-blit.frag",
    ],
    tools = [
        "//scripts:shaderinclude_py_binary",
    ],
    export_include_dirs = [
        "ui",
        "ui/shader",
    ],
    cmd = "$(location //scripts:shaderinclude_py_binary) $(location texture-blit.frag) > $(location texture-blit-frag.h)",
)

meson_genrule(
    name = "texture-blit-vert.h",
    outs = [
        "texture-blit-vert.h",
    ],
    srcs = [
        "texture-blit.vert",
    ],
    tools = [
        "//scripts:shaderinclude_py_binary",
    ],
    export_include_dirs = [
        "ui",
        "ui/shader",
    ],
    cmd = "$(location //scripts:shaderinclude_py_binary) $(location texture-blit.vert) > $(location texture-blit-vert.h)",
)
