# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_52",
    srcs = [
        "allwinner-sdhost.c",
        "aspeed_sdhci.c",
        "bcm2835_sdhost.c",
        "cadence_sdhci.c",
        "core.c",
        "npcm7xx_sdhci.c",
        "omap_mmc.c",
        "pl181.c",
        "sd.c",
        "sdhci-pci.c",
        "sdhci.c",
        "ssi-sd.c",
    ],
)

filegroup(
    name = "trace-events__60",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_sd",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
