# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "qemuutil_fg_2",
    srcs = [
        "aio-posix.c",
        "aio-wait.c",
        "aiocb.c",
        "async.c",
        "base64.c",
        "bitmap.c",
        "bitops.c",
        "block-helpers.c",
        "buffer.c",
        "bufferiszero.c",
        "cacheflush.c",
        "chardev_open.c",
        "compatfd.c",
        "coroutine-ucontext.c",
        "cpuinfo-i386.c",
        "crc-ccitt.c",
        "crc32.c",
        "crc32c.c",
        "cutils.c",
        "datadir.c",
        "defer-call.c",
        "drm.c",
        "envlist.c",
        "error-report.c",
        "error.c",
        "event.c",
        "event_notifier-posix.c",
        "fdmon-epoll.c",
        "fdmon-poll.c",
        "fifo8.c",
        "filemonitor-inotify.c",
        "getauxval.c",
        "guest-random.c",
        "hbitmap.c",
        "hexdump.c",
        "host-utils.c",
        "id.c",
        "int128.c",
        "interval-tree.c",
        "iov.c",
        "iova-tree.c",
        "keyval.c",
        "lockcnt.c",
        "log.c",
        "main-loop.c",
        "memalign.c",
        "memfd.c",
        "mmap-alloc.c",
        "module.c",
        "notify.c",
        "nvdimm-utils.c",
        "osdep.c",
        "oslib-posix.c",
        "path.c",
        "qdist.c",
        "qemu-co-shared-resource.c",
        "qemu-co-timeout.c",
        "qemu-config.c",
        "qemu-coroutine-io.c",
        "qemu-coroutine-lock.c",
        "qemu-coroutine-sleep.c",
        "qemu-coroutine.c",
        "qemu-option.c",
        "qemu-print.c",
        "qemu-progress.c",
        "qemu-sockets.c",
        "qemu-thread-posix.c",
        "qemu-timer-common.c",
        "qemu-timer.c",
        "qht.c",
        "qsp.c",
        "qtree.c",
        "range.c",
        "rcu.c",
        "readline.c",
        "reserved-region.c",
        "systemd.c",
        "thread-context.c",
        "thread-pool.c",
        "throttle.c",
        "timed-average.c",
        "transactions.c",
        "unicode.c",
        "userfaultfd.c",
        "uuid.c",
        "vfio-helpers.c",
        "vhost-user-server.c",
        "yank.c",
    ],
)

filegroup(
    name = "trace-events__5",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_util",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
