# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "arch_srcs_12",
    srcs = [
        "memory.c",
        "proxy-memory-listener.c",
    ],
)

filegroup(
    name = "system_fg_14",
    srcs = [
        "iohub.c",
        "iommu.c",
        "machine.c",
        "message.c",
        "mpqemu-link.c",
        "proxy.c",
        "remote-obj.c",
        "vfio-user-obj-stub.c",
        "vfio-user-obj.c",
    ],
)

filegroup(
    name = "trace-events__83",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_remote",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
