# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "arch_srcs_4",
    srcs = [
        "acpi-build.c",
        "acpi-common.c",
        "acpi-microvm.c",
        "amd_iommu.c",
        "e820_memory_layout.c",
        "fw_cfg.c",
        "intel_iommu.c",
        "intel_iommu_accel.c",
        "isapc.c",
        "microvm-dt.c",
        "microvm.c",
        "monitor.c",
        "multiboot.c",
        "pc.c",
        "pc_piix.c",
        "pc_q35.c",
        "pc_sysfw.c",
        "pc_sysfw_ovmf.c",
        "port92.c",
        "sgx-epc.c",
        "sgx.c",
        "tdvf-hob.c",
        "tdvf.c",
        "vapic.c",
        "vmmouse.c",
        "vmport.c",
        "x86-common.c",
        "x86-cpu.c",
        "x86-iommu.c",
        "x86.c",
    ],
)

filegroup(
    name = "qemuutil_fg_10",
    srcs = [
        "sgx-hmp-stub.c",
    ],
)

filegroup(
    name = "trace-events__36",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_i386",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
