# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_flags", "meson_cc_headers")

meson_cc_headers(
    name = "inc_tests_fp",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)

meson_cc_flags(
    name = "sfcflags",
    flags = [
        "-DINLINE_LEVEL=5",
        "-DSOFTFLOAT_FAST_DIV32TO16",
        "-DSOFTFLOAT_FAST_DIV64TO32",
        "-DSOFTFLOAT_FAST_INT64",
        "-DSOFTFLOAT_ROUND_ODD",
    ],
)

meson_cc_flags(
    name = "tfcflags",
    flags = [
        "-DEXTFLOAT80",
        "-DFLOAT128",
        "-DFLOAT16",
        "-DFLOAT64",
        "-DFLOAT_ROUND_ODD",
        "-DLONG_DOUBLE_IS_EXTFLOAT80",
    ],
)
