# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

filegroup(
    name = "qemuutil_fg_5",
    srcs = [
        "async-run-on-cpu.c",
        "bdrv-next-monitor-owned.c",
        "blk-commit-all.c",
        "blk-exp-close-all.c",
        "blockdev-close-all-bdrv-states.c",
        "change-state-handler.c",
        "cmos.c",
        "cpu-get-clock.c",
        "cpus-queue.c",
        "cpus-virtual-clock.c",
        "dump.c",
        "fdset.c",
        "fw_cfg.c",
        "get-vm-name.c",
        "graph-lock.c",
        "hmp-cmd-info_mem.c",
        "hmp-cmd-info_sev.c",
        "hmp-cmd-info_tlb.c",
        "hmp-cmds-hw-s390x.c",
        "hmp-cmds-target-i386.c",
        "hotplug-stubs.c",
        "icount.c",
        "iothread-lock-block.c",
        "iothread-lock.c",
        "is-daemonized.c",
        "kvm.c",
        "migr-blocker.c",
        "monitor-core.c",
        "monitor-internal.c",
        "physmem.c",
        "qemu-timer-notify-cb.c",
        "qmp-arm-gic.c",
        "qmp-command-available.c",
        "qmp-cpu-s390x-kvm.c",
        "qmp-cpu-s390x.c",
        "qmp-cpu.c",
        "qmp-i386-rtc.c",
        "qmp-i386-sev.c",
        "qmp-i386-sgx.c",
        "qmp-i386-xen.c",
        "qmp-quit.c",
        "qtest.c",
        "ram-block.c",
        "replay-mode.c",
        "replay-tools.c",
        "replay.c",
        "runstate-check.c",
        "sysbus.c",
        "trace-control.c",
        "uuid.c",
        "vm-stop.c",
        "vmstate.c",
        "win32-kbd-hook.c",
        "xen-hw-stub.c",
    ],
)
