# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_29",
    srcs = [
        "aspeed_i3c.c",
        "core.c",
        "dw-i3c.c",
        "mock-i3c-target.c",
    ],
)

filegroup(
    name = "trace-events__35",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_i3c",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
