# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "qemuutil_fg_19",
    srcs = [
        "rocker-stubs.c",
    ],
)

filegroup(
    name = "system_fg_41",
    srcs = [
        "rocker-hmp-cmds.c",
        "rocker.c",
        "rocker_desc.c",
        "rocker_fp.c",
        "rocker_of_dpa.c",
        "rocker_world.c",
    ],
)

meson_cc_headers(
    name = "inc_hw_net_rocker",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
