# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_79",
    srcs = [
        "replay-audio.c",
        "replay-char.c",
        "replay-debugging.c",
        "replay-events.c",
        "replay-input.c",
        "replay-internal.c",
        "replay-net.c",
        "replay-random.c",
        "replay-snapshot.c",
        "replay-time.c",
        "replay.c",
        "stubs-system.c",
    ],
)

filegroup(
    name = "trace-events__80",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_replay",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
