# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "system_fg_25",
    srcs = [
        "bcm2835_dma.c",
        "i82374.c",
        "i8257.c",
        "omap_dma.c",
        "pl080.c",
        "pl330.c",
        "rc4030.c",
        "sifive_pdma.c",
        "soc_dma.c",
        "sparc32_dma.c",
        "xilinx_axidma.c",
        "xlnx-zdma.c",
        "xlnx-zynq-devcfg.c",
        "xlnx_csu_dma.c",
        "xlnx_dpdma.c",
    ],
)

filegroup(
    name = "trace-events__31",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_dma",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
