# Copyright (C) 2025-2026 The Magma GPU Project
# SPDX-License-Identifier: Apache-2.0
#
# Generated via:
#   https://github.com/mesonbuild/meson/tree/master/mesonbuild/convert
#
# Submit patches, do not hand-edit.

load("//bazel:meson_rules.bzl", "meson_cc_headers")

filegroup(
    name = "arch_srcs_5",
    srcs = [
        "apic.c",
        "clock.c",
        "i8254.c",
        "i8259.c",
        "ioapic.c",
        "xen_evtchn.c",
        "xen_gnttab.c",
        "xen_overlay.c",
        "xen_primary_console.c",
        "xen_xenstore.c",
        "xenstore_impl.c",
    ],
)

filegroup(
    name = "qemuutil_fg_11",
    srcs = [
        "xen-stubs.c",
    ],
)

filegroup(
    name = "trace-events__38",
    srcs = [
        "trace-events",
    ],
)

meson_cc_headers(
    name = "inc_hw_i386_kvm",
    hdrs = glob(["**/*.h", "**/*.hpp", "**/*.inl", "**/*.inc"], allow_empty = True),
)
